/**
 * Shared drawing primitives for the build-time images.
 *
 * Used by make-og.mjs (the social card) and make-wall-gif.mjs (the animated
 * listing preview), so the two cannot drift apart in palette or letterform.
 *
 * There is no font rasteriser in Node and no canvas dependency here on
 * purpose: the same constraint that lets src/core run in the test suite lets
 * these images be generated by `npm run build` on any machine.
 */

/* ------------------------------------------------------------- palette -- */

export const INK = [17, 20, 26];
export const PAPER = [244, 245, 247];
export const WHITE = [255, 255, 255];
export const ACCENT = [67, 56, 202];
export const MUTED = [84, 92, 107];
export const LINE = [223, 227, 234];
export const OK = [21, 128, 61];
export const OK_SOFT = [220, 252, 231];

/** The six decorative hues from tokens.css. */
export const HUES = [
  [67, 56, 202],
  [109, 40, 217],
  [162, 28, 175],
  [3, 105, 161],
  [21, 94, 117],
  [15, 118, 110],
];

/* -------------------------------------------------------------- canvas -- */

/**
 * @param {number} width @param {number} height
 * @param {[number, number, number]} rgb
 */
export function makeCanvas(width, height, [r, g, b]) {
  const data = new Uint8ClampedArray(width * height * 4);
  for (let i = 0; i < data.length; i += 4) {
    data[i] = r;
    data[i + 1] = g;
    data[i + 2] = b;
    data[i + 3] = 255;
  }
  return { data, width, height };
}

/** @param {{data: Uint8ClampedArray, width: number, height: number}} c */
export function cloneCanvas(c) {
  return { data: new Uint8ClampedArray(c.data), width: c.width, height: c.height };
}

export function fillRect(dst, x0, y0, w, h, [r, g, b]) {
  const xs = Math.max(0, Math.round(x0));
  const ys = Math.max(0, Math.round(y0));
  const xe = Math.min(dst.width, Math.round(x0 + w));
  const ye = Math.min(dst.height, Math.round(y0 + h));
  for (let y = ys; y < ye; y++) {
    let o = (y * dst.width + xs) * 4;
    for (let x = xs; x < xe; x++) {
      dst.data[o] = r;
      dst.data[o + 1] = g;
      dst.data[o + 2] = b;
      dst.data[o + 3] = 255;
      o += 4;
    }
  }
}

/** A filled circle, anti-aliased by 3x3 sampling. */
export function fillCircle(dst, cx, cy, radius, [r, g, b]) {
  const x0 = Math.max(0, Math.floor(cx - radius - 1));
  const y0 = Math.max(0, Math.floor(cy - radius - 1));
  const x1 = Math.min(dst.width, Math.ceil(cx + radius + 1));
  const y1 = Math.min(dst.height, Math.ceil(cy + radius + 1));
  const rr = radius * radius;
  for (let py = y0; py < y1; py++) {
    for (let px = x0; px < x1; px++) {
      let hits = 0;
      for (let sy = 0; sy < 3; sy++) {
        const fy = py + (sy + 0.5) / 3 - cy;
        for (let sx = 0; sx < 3; sx++) {
          const fx = px + (sx + 0.5) / 3 - cx;
          if (fx * fx + fy * fy <= rr) hits++;
        }
      }
      if (!hits) continue;
      const a = hits / 9;
      const o = (py * dst.width + px) * 4;
      dst.data[o] = dst.data[o] * (1 - a) + r * a;
      dst.data[o + 1] = dst.data[o + 1] * (1 - a) + g * a;
      dst.data[o + 2] = dst.data[o + 2] * (1 - a) + b * a;
      dst.data[o + 3] = 255;
    }
  }
}

/** Copy one canvas into another, optionally clipping to a width. */
export function blit(dst, src, x0, y0, clipWidth = Infinity) {
  const limit = Math.min(src.width, clipWidth);
  for (let y = 0; y < src.height; y++) {
    const dy = y0 + y;
    if (dy < 0 || dy >= dst.height) continue;
    for (let x = 0; x < limit; x++) {
      const dx = x0 + x;
      if (dx < 0 || dx >= dst.width) continue;
      const s = (y * src.width + x) * 4;
      const d = (dy * dst.width + dx) * 4;
      dst.data[d] = src.data[s];
      dst.data[d + 1] = src.data[s + 1];
      dst.data[d + 2] = src.data[s + 2];
      dst.data[d + 3] = 255;
    }
  }
}

/* -------------------------------------------------------- stencil type -- */

/*
  A stencil alphabet, drawn as polygons.

  Squared, stencil-cut letterforms suit an app whose entire subject is squares
  on a grid, so this reads as a deliberate display face rather than a
  workaround for the missing font rasteriser.

  Coordinates are fractions of the cap height: x from 0 to WIDTH, y from 0 at
  the cap line to 1 at the baseline. STROKE is the stem thickness.
*/
export const STROKE = 0.2;
export const WIDTH = 0.62;

const S = STROKE;
const W = WIDTH;

const box = (x, y, w, h) => [
  [x, y],
  [x + w, y],
  [x + w, y + h],
  [x, y + h],
];

/** @type {Record<string, number[][][]>} */
export const GLYPHS = {
  A: [
    [[0, 1], [S, 1], [W / 2 + S / 2, 0], [W / 2 - S / 2, 0]],
    [[W - S, 1], [W, 1], [W / 2 + S / 2, 0], [W / 2 - S / 2, 0]],
    box(S * 0.55, 0.58, W - S * 1.1, S * 0.9),
  ],
  B: [
    box(0, 0, S, 1), box(0, 0, W - S * 0.6, S), box(0, (1 - S) / 2, W - S * 0.6, S),
    box(0, 1 - S, W - S * 0.6, S), box(W - S, S, S, (1 - S) / 2 - S),
    box(W - S, (1 + S) / 2, S, (1 - S) / 2 - S),
  ],
  C: [box(0, 0, W, S), box(0, 0, S, 1), box(0, 1 - S, W, S)],
  // Flat left stem with cut corners on the right, which is what keeps a
  // squared D from reading as an O.
  D: [
    box(0, 0, S, 1), box(0, 0, W - S * 1.1, S), box(0, 1 - S, W - S * 1.1, S),
    [
      [W - S * 1.1, 0], [W, S * 1.15], [W, 1 - S * 1.15], [W - S * 1.1, 1],
      [W - S * 1.1, 1 - S], [W - S, 1 - S * 1.5], [W - S, S * 1.5], [W - S * 1.1, S],
    ],
  ],
  E: [box(0, 0, S, 1), box(0, 0, W, S), box(0, (1 - S) / 2, W * 0.82, S), box(0, 1 - S, W, S)],
  F: [box(0, 0, S, 1), box(0, 0, W, S), box(0, (1 - S) / 2, W * 0.82, S)],
  // The spur is what stops a squared G reading as a C.
  G: [
    box(0, 0, W, S), box(0, 0, S, 1), box(0, 1 - S, W, S),
    box(W - S, 0.5, S, 0.5), box(W * 0.52, 0.5 - S / 2, W * 0.48, S),
  ],
  H: [box(0, 0, S, 1), box(W - S, 0, S, 1), box(0, (1 - S) / 2, W, S)],
  I: [box((W - S) / 2, 0, S, 1)],
  K: [
    box(0, 0, S, 1),
    [[W - S, 0], [W, 0], [S + S * 0.9, 0.52], [S, 0.52]],
    [[S, 0.48], [S + S * 0.9, 0.48], [W, 1], [W - S, 1]],
  ],
  L: [box(0, 0, S, 1), box(0, 1 - S, W, S)],
  M: [
    box(0, 0, S, 1), box(W * 1.18 - S, 0, S, 1),
    [[0, 0], [S, 0], [W * 0.59 + S / 2, 0.72], [W * 0.59 - S / 2, 0.72]],
    [[W * 1.18 - S, 0], [W * 1.18, 0], [W * 0.59 + S / 2, 0.72], [W * 0.59 - S / 2, 0.72]],
  ],
  N: [box(0, 0, S, 1), box(W - S, 0, S, 1), [[0, 0], [S, 0], [W, 1], [W - S, 1]]],
  O: [box(0, 0, W, S), box(0, 1 - S, W, S), box(0, 0, S, 1), box(W - S, 0, S, 1)],
  P: [box(0, 0, S, 1), box(0, 0, W, S), box(0, (1 - S) / 2, W, S), box(W - S, S, S, (1 - S) / 2 - S)],
  R: [
    box(0, 0, S, 1), box(0, 0, W, S), box(0, (1 - S) / 2, W, S), box(W - S, S, S, (1 - S) / 2 - S),
    [[W - S * 1.7, (1 + S) / 2], [W - S * 0.7, (1 + S) / 2], [W, 1], [W - S, 1]],
  ],
  S: [
    box(0, 0, W, S), box(0, 0, S, (1 + S) / 2 - S), box(0, (1 - S) / 2, W, S),
    box(W - S, (1 - S) / 2, S, (1 + S) / 2 - S), box(0, 1 - S, W, S),
  ],
  T: [box(0, 0, W, S), box((W - S) / 2, 0, S, 1)],
  U: [box(0, 0, S, 1), box(W - S, 0, S, 1), box(0, 1 - S, W, S)],
  V: [
    [[0, 0], [S, 0], [W / 2 + S / 2, 1], [W / 2 - S / 2, 1]],
    [[W - S, 0], [W, 0], [W / 2 + S / 2, 1], [W / 2 - S / 2, 1]],
  ],
  W: [
    [[0, 0], [S, 0], [W * 0.42 + S / 2, 1], [W * 0.42 - S / 2, 1]],
    [[W * 0.59, 0], [W * 0.59 + S, 0], [W * 0.42 + S / 2, 1], [W * 0.42 - S / 2, 1]],
    [[W * 0.59, 0], [W * 0.59 + S, 0], [W * 1.18 - S / 2, 1], [W * 1.18 - S * 1.5, 1]],
    [[W * 1.18 - S, 0], [W * 1.18, 0], [W * 1.18 - S / 2, 1], [W * 1.18 - S * 1.5, 1]],
  ],
  X: [
    [[0, 0], [S, 0], [W, 1], [W - S, 1]],
    [[W - S, 0], [W, 0], [S, 1], [0, 1]],
  ],
  Y: [
    [[0, 0], [S, 0], [W / 2 + S / 2, 0.55], [W / 2 - S / 2, 0.55]],
    [[W - S, 0], [W, 0], [W / 2 + S / 2, 0.55], [W / 2 - S / 2, 0.55]],
    box((W - S) / 2, 0.5, S, 0.5),
  ],
  Z: [box(0, 0, W, S), box(0, 1 - S, W, S), [[W - S, S], [W, S], [S, 1 - S], [0, 1 - S]]],
  '0': [box(0, 0, W, S), box(0, 1 - S, W, S), box(0, 0, S, 1), box(W - S, 0, S, 1)],
  '.': [box(0, 1 - S, S, S)],
  ',': [box(0, 1 - S, S, S), [[S * 0.15, 1], [S, 1], [S * 0.45, 1 + S * 0.85], [0, 1 + S * 0.85]]],
  '-': [box(0, (1 - S) / 2, W * 0.75, S)],
  '/': [[[W - S, 0], [W, 0], [S, 1], [0, 1]]],
  ':': [box(0, 0.28, S, S), box(0, 1 - S, S, S)],
  ' ': [],
};

/** Advance width per glyph, as a fraction of cap height. */
export const ADVANCE = {
  '.': STROKE * 1.6,
  ',': STROKE * 1.6,
  ':': STROKE * 1.6,
  I: STROKE * 2.2,
  ' ': WIDTH * 0.5,
  M: WIDTH * 1.18,
  W: WIDTH * 1.18,
};

export const TRACKING = 0.17;

/** @param {string} text @param {number} h cap height in pixels */
export function measure(text, h) {
  let total = 0;
  for (const ch of text) total += (ADVANCE[ch.toUpperCase()] ?? WIDTH) * h + TRACKING * h;
  return Math.max(0, total - TRACKING * h);
}

/**
 * Even-odd point-in-polygon test.
 * @param {number[][]} poly @param {number} px @param {number} py
 */
function inPolygon(poly, px, py) {
  let inside = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i];
    const [xj, yj] = poly[j];
    if (yi > py !== yj > py && px < ((xj - xi) * (py - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

/**
 * Fill the union of polygons with 3x3 supersampled coverage, so the diagonals
 * in A, K, N, R, V, W, X and Y are not visibly jagged.
 */
export function fillPolygons(dst, polys, [r, g, b]) {
  if (polys.length === 0) return;
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const poly of polys) {
    for (const [px, py] of poly) {
      if (px < minX) minX = px;
      if (px > maxX) maxX = px;
      if (py < minY) minY = py;
      if (py > maxY) maxY = py;
    }
  }
  const x0 = Math.max(0, Math.floor(minX));
  const y0 = Math.max(0, Math.floor(minY));
  const x1 = Math.min(dst.width, Math.ceil(maxX) + 1);
  const y1 = Math.min(dst.height, Math.ceil(maxY) + 1);

  for (let py = y0; py < y1; py++) {
    for (let px = x0; px < x1; px++) {
      let hits = 0;
      for (let sy = 0; sy < 3; sy++) {
        const fy = py + (sy + 0.5) / 3;
        for (let sx = 0; sx < 3; sx++) {
          const fx = px + (sx + 0.5) / 3;
          for (const poly of polys) {
            if (inPolygon(poly, fx, fy)) {
              hits++;
              break;
            }
          }
        }
      }
      if (!hits) continue;
      const a = hits / 9;
      const o = (py * dst.width + px) * 4;
      dst.data[o] = dst.data[o] * (1 - a) + r * a;
      dst.data[o + 1] = dst.data[o + 1] * (1 - a) + g * a;
      dst.data[o + 2] = dst.data[o + 2] * (1 - a) + b * a;
      dst.data[o + 3] = 255;
    }
  }
}

/**
 * Draw a string at a cap-line origin.
 *
 * Throws on a glyph nobody has drawn, so a copy change fails the build rather
 * than shipping a headline with a hole in it.
 *
 * @returns {number} x just past the final glyph
 */
export function drawText(dst, text, x, y, h, colour, { maxChars = Infinity } = {}) {
  const polys = [];
  let cursor = x;
  let drawn = 0;
  for (const ch of text) {
    const key = ch.toUpperCase();
    const glyph = GLYPHS[key];
    if (glyph === undefined) throw new Error(`No stencil glyph for ${JSON.stringify(ch)}. Add one to GLYPHS.`);
    if (drawn < maxChars) {
      for (const poly of glyph) polys.push(poly.map(([px, py]) => [cursor + px * h, y + py * h]));
    }
    cursor += (ADVANCE[key] ?? WIDTH) * h + TRACKING * h;
    drawn++;
  }
  fillPolygons(dst, polys, colour);
  return cursor - TRACKING * h;
}

/* ------------------------------------------------------------ the mark -- */

/** Rounded rectangle, built from the primitives above. */
export function roundedRect(dst, x, y, w, h, r, colour) {
  const rad = Math.min(r, w / 2, h / 2);
  fillRect(dst, x + rad, y, w - rad * 2, h, colour);
  fillRect(dst, x, y + rad, rad, h - rad * 2, colour);
  fillRect(dst, x + w - rad, y + rad, rad, h - rad * 2, colour);
  fillCircle(dst, x + rad, y + rad, rad, colour);
  fillCircle(dst, x + w - rad, y + rad, rad, colour);
  fillCircle(dst, x + rad, y + h - rad, rad, colour);
  fillCircle(dst, x + w - rad, y + h - rad, rad, colour);
}

/**
 * The Etch mark: the same geometry as public/favicon.svg, scaled into a box.
 *
 * Kept identical to the favicon on purpose, so the icon in the browser tab,
 * the icon on the home screen and the icon in the middle of the code are all
 * one drawing rather than three that drift.
 */
export function drawMark(dst, x, y, size, bg, fg) {
  const u = size / 32;
  roundedRect(dst, x, y, size, size, 8 * u, bg);

  // The finder ring, which is the one shape everyone reads as "QR code".
  const rx = x + 7 * u;
  const ry = y + 7 * u;
  const ring = 8 * u;
  const t = Math.max(1, 2.6 * u);
  fillRect(dst, rx, ry, ring, t, fg);
  fillRect(dst, rx, ry + ring - t, ring, t, fg);
  fillRect(dst, rx, ry, t, ring, fg);
  fillRect(dst, rx + ring - t, ry, t, ring, fg);
  fillRect(dst, x + 10.2 * u, y + 10.2 * u, 2.4 * u, 2.4 * u, fg);

  // Scattered modules, so it reads as a code rather than only a finder.
  fillRect(dst, x + 19 * u, y + 7 * u, 6 * u, 2.6 * u, fg);
  fillRect(dst, x + 22.4 * u, y + 9.6 * u, 2.6 * u, 4 * u, fg);
  fillRect(dst, x + 7 * u, y + 19 * u, 2.6 * u, 6 * u, fg);
  fillRect(dst, x + 12 * u, y + 19 * u, 3.4 * u, 2.6 * u, fg);
  fillRect(dst, x + 19 * u, y + 19 * u, 6 * u, 6 * u, fg);
}

/**
 * A tick, drawn as two angled strokes.
 *
 * Two axis-aligned rectangles read as a blob at badge size; a real tick needs
 * the diagonals, which is what the polygon filler is for.
 */
export function drawTick(dst, cx, cy, size, colour) {
  const t = size * 0.26;
  const short = [
    [cx - size * 0.42, cy - size * 0.02],
    [cx - size * 0.42 + t * 0.8, cy - size * 0.02 - t * 0.5],
    [cx - size * 0.06, cy + size * 0.3],
    [cx - size * 0.06 - t * 0.8, cy + size * 0.3 + t * 0.5],
  ];
  const long = [
    [cx + size * 0.46, cy - size * 0.38],
    [cx + size * 0.46 + t * 0.55, cy - size * 0.38 + t * 0.7],
    [cx - size * 0.08, cy + size * 0.36],
    [cx - size * 0.08 - t * 0.55, cy + size * 0.36 - t * 0.7],
  ];
  fillPolygons(dst, [short, long], colour);
}
