/**
 * Extract just the Bootstrap Icons this app uses into a single module.
 *
 * The brief asked for Bootstrap Icons as the icon set. Shipping the icon font
 * or the full sprite would cost well over 100KB for the twenty-odd glyphs
 * actually used, and the font route also means a second network request for
 * something this app promises never to fetch. Inlining the path data costs
 * about 3KB and keeps the set exactly as specified.
 *
 * Run: node scripts/build-icons.mjs
 * Output: src/components/icons.js (committed, so the build needs no icon dep)
 */

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const iconDir = join(here, '..', 'node_modules', 'bootstrap-icons', 'icons');
const out = join(here, '..', 'src', 'components', 'icons.js');

const NAMES = [
  // payload types
  'link-45deg', 'card-text', 'wifi', 'person-vcard', 'envelope', 'chat-dots',
  'telephone', 'geo-alt', 'calendar-event', 'bank', 'phone',
  // status
  'check-circle-fill', 'exclamation-triangle-fill', 'x-circle-fill', 'info-circle-fill',
  'shield-check', 'patch-check',
  // actions and chrome
  'download', 'filetype-svg', 'filetype-pdf', 'file-earmark-image', 'file-earmark-zip',
  'sliders', 'palette', 'printer', 'chevron-right', 'sun', 'moon-stars', 'github',
  'box-arrow-up-right', 'clipboard', 'clipboard-check', 'upload', 'arrow-repeat',
  'search', 'x-lg', 'eye', 'link', 'grid-3x3-gap', 'lightning-charge', 'wifi-off',
  'arrow-left', 'plus-lg', 'dash-lg', 'question-circle', 'table', 'trash',
  // Explainer sections
  'scissors', 'aspect-ratio', 'droplet', 'journal-text', 'code-slash',
];

const paths = {};
for (const name of NAMES) {
  const svg = await readFile(join(iconDir, `${name}.svg`), 'utf8');
  // Everything between the opening <svg ...> and </svg> is the drawing.
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '').trim();
  paths[name] = inner.replace(/\s+/g, ' ');
}

const banner = `/**
 * Bootstrap Icons, inlined.
 *
 * GENERATED by scripts/build-icons.mjs. Do not edit by hand.
 * Bootstrap Icons is MIT licensed, (c) 2019-2024 The Bootstrap Authors.
 * https://github.com/twbs/icons
 *
 * All glyphs are drawn on a 16x16 viewBox.
 */

`;

const body = `export const ICON_PATHS = ${JSON.stringify(paths, null, 2)};\n`;
await writeFile(out, banner + body, 'utf8');

const bytes = Buffer.byteLength(banner + body);
console.log(`Wrote ${NAMES.length} icons to src/components/icons.js (${(bytes / 1024).toFixed(1)}KB)`);
